---
application:
  name: service1-dev
server:
  port: 8085
management:
  port: 9085
spring:
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        trace: true      